<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251204233519 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE learning_path (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4D04C797B03A8386 ON learning_path (created_by_id)');
        $this->addSql('CREATE TABLE learning_path_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position INT NOT NULL, learning_path_id INT NOT NULL, sop_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_885CE12E1DCBEE98 ON learning_path_item (learning_path_id)');
        $this->addSql('CREATE INDEX IDX_885CE12ED52982EE ON learning_path_item (sop_id)');
        $this->addSql('CREATE TABLE sop (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, summary TEXT DEFAULT NULL, difficulty INT DEFAULT NULL, department VARCHAR(100) DEFAULT NULL, status VARCHAR(20) NOT NULL, version_number INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, category_id INT NOT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1B96094F12469DE2 ON sop (category_id)');
        $this->addSql('CREATE INDEX IDX_1B96094FB03A8386 ON sop (created_by_id)');
        $this->addSql('CREATE TABLE sop_tag (sop_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (sop_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_2F3A39EDD52982EE ON sop_tag (sop_id)');
        $this->addSql('CREATE INDEX IDX_2F3A39EDBAD26311 ON sop_tag (tag_id)');
        $this->addSql('CREATE TABLE sopstep (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, step_number INT NOT NULL, content TEXT NOT NULL, attachment VARCHAR(255) DEFAULT NULL, sop_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_226169A8D52982EE ON sopstep (sop_id)');
        $this->addSql('CREATE TABLE sopversion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, version_number INT NOT NULL, content JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, sop_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F30E85B5D52982EE ON sopversion (sop_id)');
        $this->addSql('CREATE INDEX IDX_F30E85B5B03A8386 ON sopversion (created_by_id)');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE user_progress (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(50) NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, owner_id INT NOT NULL, sop_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C28C16467E3C61F9 ON user_progress (owner_id)');
        $this->addSql('CREATE INDEX IDX_C28C1646D52982EE ON user_progress (sop_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE learning_path ADD CONSTRAINT FK_4D04C797B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE learning_path_item ADD CONSTRAINT FK_885CE12E1DCBEE98 FOREIGN KEY (learning_path_id) REFERENCES learning_path (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE learning_path_item ADD CONSTRAINT FK_885CE12ED52982EE FOREIGN KEY (sop_id) REFERENCES sop (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sop ADD CONSTRAINT FK_1B96094F12469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sop ADD CONSTRAINT FK_1B96094FB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE sop_tag ADD CONSTRAINT FK_2F3A39EDD52982EE FOREIGN KEY (sop_id) REFERENCES sop (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sop_tag ADD CONSTRAINT FK_2F3A39EDBAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sopstep ADD CONSTRAINT FK_226169A8D52982EE FOREIGN KEY (sop_id) REFERENCES sop (id)');
        $this->addSql('ALTER TABLE sopversion ADD CONSTRAINT FK_F30E85B5D52982EE FOREIGN KEY (sop_id) REFERENCES sop (id)');
        $this->addSql('ALTER TABLE sopversion ADD CONSTRAINT FK_F30E85B5B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE user_progress ADD CONSTRAINT FK_C28C16467E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_progress ADD CONSTRAINT FK_C28C1646D52982EE FOREIGN KEY (sop_id) REFERENCES sop (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE learning_path DROP CONSTRAINT FK_4D04C797B03A8386');
        $this->addSql('ALTER TABLE learning_path_item DROP CONSTRAINT FK_885CE12E1DCBEE98');
        $this->addSql('ALTER TABLE learning_path_item DROP CONSTRAINT FK_885CE12ED52982EE');
        $this->addSql('ALTER TABLE sop DROP CONSTRAINT FK_1B96094F12469DE2');
        $this->addSql('ALTER TABLE sop DROP CONSTRAINT FK_1B96094FB03A8386');
        $this->addSql('ALTER TABLE sop_tag DROP CONSTRAINT FK_2F3A39EDD52982EE');
        $this->addSql('ALTER TABLE sop_tag DROP CONSTRAINT FK_2F3A39EDBAD26311');
        $this->addSql('ALTER TABLE sopstep DROP CONSTRAINT FK_226169A8D52982EE');
        $this->addSql('ALTER TABLE sopversion DROP CONSTRAINT FK_F30E85B5D52982EE');
        $this->addSql('ALTER TABLE sopversion DROP CONSTRAINT FK_F30E85B5B03A8386');
        $this->addSql('ALTER TABLE user_progress DROP CONSTRAINT FK_C28C16467E3C61F9');
        $this->addSql('ALTER TABLE user_progress DROP CONSTRAINT FK_C28C1646D52982EE');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE learning_path');
        $this->addSql('DROP TABLE learning_path_item');
        $this->addSql('DROP TABLE sop');
        $this->addSql('DROP TABLE sop_tag');
        $this->addSql('DROP TABLE sopstep');
        $this->addSql('DROP TABLE sopversion');
        $this->addSql('DROP TABLE tag');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_progress');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
